spring.application.name=springboot-feature-demo

# for ConfigurationProperties
currency-service.url=http://dev.in28minutes.com
currency-service.username=devusername
currency-service.key=devkey

# for mvc
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.mvc.format.date=yyyy-MM-dd
